apiVersion: v1
kind: ConfigMap
metadata:
  name: data-api-fluent-bit-config
  labels:
    {{- include "tech-test.labels.data-api" . | nindent 4 }}
data:
  fluent-bit.conf: |
    [INPUT]
        Name              tail
        Path              /configured_path/*.txt
        Refresh_Interval  10
        Rotate_Wait       30
        Tag               data_api

    [FILTER]
        Name modify
        Match data_api
        Add kubernetes_pod_name ${POD_NAME}
        Add application_name data_api

    [OUTPUT]
        Name http
        Match data_api
        host victoria-logs-victoria-logs-single-server.victoria-logs
        port 9428
        uri /insert/jsonline?_stream_fields=kubernetes_pod_name,application_name&_msg_field=log&_time_field=date
        format json_lines
        json_date_format iso8601
