apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tech-test.fullname.data-api" . }}
  labels:
    {{- include "tech-test.labels.data-api" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tech-test.selectorLabels.data-api" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tech-test.labels.data-api" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tech-test.serviceAccountName.data-api" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: setup-permissions
        securityContext:
          {{- toYaml .Values.dataApi.initContainerSecurityContext | nindent 10 }}
        image: busybox
        command: ['sh', '-c', 'chown -R 65535:65535 /configured_path']
        {{- with .Values.dataApi.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.dataApi.image.repository }}:{{ .Values.dataApi.image.tag }}"
          imagePullPolicy: {{ .Values.dataApi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          startupProbe:
            {{- toYaml .Values.dataApi.startupProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.dataApi.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.dataApi.resources | nindent 12 }}
          {{- with .Values.dataApi.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.dataApi.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
