---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tech-test.serviceAccountName.data-api" . }}
  labels:
    {{- include "tech-test.labels.data-api" . | nindent 4 }}
  {{- with .Values.dataApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.dataApi.serviceAccount.automount }}
