apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tech-test.fullname.backend-api" . }}-secret
  labels:
    {{- include "tech-test.labels.backend-api" . | nindent 4 }}
type: Opaque
stringData:
    externalIntegrationKey: {{ .Values.backendApi.externalIntegrationKey | required "Please provide a value for externalIntegrationKey" }}
