---
- name: Install stack
  gather_facts: false
  hosts: localhost
  vars_files:
    - vault_{{ env }}.yaml
  tasks:
    - name: Check if Helm is installed
      ansible.builtin.command:
        cmd: helm version --short
      register: helm_installed
      changed_when: helm_installed.rc != 0
      ignore_errors: true

    - name: Download Helm install script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        dest: /tmp/get-helm-3
        mode: '0755'
      when: helm_installed.failed

    - name: Add Victoria Metrics chart repo
      kubernetes.core.helm_repository:
        name: vm
        repo_url: "https://victoriametrics.github.io/helm-charts/"

    - name: Add Metrics Server chart repo
      kubernetes.core.helm_repository:
        name: metrics-server
        repo_url: "https://kubernetes-sigs.github.io/metrics-server/"

    - name: Deploy Metrics Server chart
      kubernetes.core.helm:
        name: metrics-server
        chart_ref: metrics-server/metrics-server
        release_namespace: kube-system
        wait: true
        values:
          args:
            - "--kubelet-insecure-tls"

    - name: Deploy Victoria Logs chart
      kubernetes.core.helm:
        name: victoria-logs
        chart_ref: vm/victoria-logs-single
        release_namespace: victoria-logs
        create_namespace: true
        wait: true
        values:
          fluent-bit:
            enabled: true

    - name: Deploy Victoria Metrics k8s stack
      kubernetes.core.helm:
        name: vm
        chart_ref: vm/victoria-metrics-k8s-stack
        release_namespace: vm
        create_namespace: true
        wait: true

    - name: Deploy Tech test chart from local path
      kubernetes.core.helm:
        name: technical-test
        chart_ref: ../helm
        release_namespace: tech-test
        create_namespace: true
        wait: true
        values:
          backendApi:
            externalIntegrationKey: "{{ external_integration_key }}"

    # Default provisioned dashboards were not working for me due to the bug
    # https://github.com/google/cadvisor/issues/3336
    - name: Create a Custom dashboard for Pods
      kubernetes.core.k8s:
        state: present
        src: files/grafana-dashboard.yaml
        namespace: vm
