replicaCount: 1

dataApi:
  image:
    repository: data-api
    pullPolicy: Never # set to Never because local build cache is used
    tag: "latest" # same as above
  serviceAccount:
    automount: true
    annotations: {}
    name: ""
  volumes:
    - name: data-api-config-volume
      emptyDir: {}
  volumeMounts:
    - name: data-api-config-volume
      mountPath: /configured_path
  initContainerSecurityContext:
    readOnlyRootFilesystem: true
    capabilities:
      drop: ["all"]
      add: ["CHOWN"]
    runAsUser: 0
    runAsNonRoot: false
  startupProbe:
    httpGet:
      path: /
      port: 5000
    failureThreshold: 2
    periodSeconds: 10
    timeoutSeconds: 5
  readinessProbe:
    httpGet:
      path: /health_check
      port: 5000
  resources: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsUser: 65534
  runAsGroup: 65534
  fsGroup: 65534

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

nodeSelector: {}
tolerations: []
affinity: {}
